export const LOGIN_REQUEST='LOGIN_REQUEST'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGOUT='LOGOUT'

export const GET_TEACHERS_LIST_REQUEST='GET_TEACHERS_LIST_REQUEST'
export const GET_TEACHERS_LIST_SUCCESS='GET_TEACHERS_LIST_SUCCESS'
export const GET_TEACHERS_LIST_FAIL='GET_TEACHERS_LIST_FAIL'

export const GET_STUDENT_LIST_REQUEST='GET_STUDENT_LIST_REQUEST'
export const GET_STUDENT_LIST_SUCCESS='GET_STUDENT_LIST_SUCCESS'
export const GET_STUDENT_LIST_FAIL='GET_STUDENT_LIST_FAIL'

export const GET_CLASS_LIST_REQUEST='GET_CLASS_LIST_REQUEST'
export const GET_CLASS_LIST_SUCCESS='GET_CLASS_LIST_SUCCESS'
export const GET_CLASS_LIST_FAIL='GET_CLASS_LIST_FAIL'

export const ADD_CLASS_REQUEST='ADD_CLASS_REQUEST'
export const ADD_CLASS_SUCCESS='ADD_CLASS_SUCCESS'
export const ADD_CLASS_FAIL='ADD_CLASS_FAIL'

export const DELETE_CLASS_REQUEST='DELETE_CLASS_REQUEST'
export const DELETE_CLASS_SUCCESS='DELETE_CLASS_SUCCESS'
export const DELETE_CLASS_FAIL='DELETE_CLASS_FAIL'

export const GET_ADMIN_REQUEST='GET_ADMIN_REQUEST'
export const GET_ADMIN_SUCCESS='GET_ADMIN_SUCCESS'
export const GET_ADMIN_FAIL='GET_ADMIN_FAIL'

export const ADD_STUDENT_REQUEST='ADD_STUDENT_REQUEST'
export const ADD_STUDENT_SUCCESS='ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAIL='ADD_STUDENT_FAIL'

export const ADD_TEACHER_REQUEST='ADD_TEACHER_REQUEST'
export const ADD_TEACHER_SUCCESS='ADD_TEACHER_SUCCESS'
export const ADD_TEACHER_FAIL='ADD_TEACHER_FAIL'

export const DELETE_TEACHER_REQUEST='DELETE_TEACHER_REQUEST'
export const DELETE_TEACHER_SUCCESS='DELETE_TEACHER_SUCCESS'
export const DELETE_TEACHER_FAIL='DELETE_TEACHER_FAIL'

export const DELETE_STUDENT_REQUEST='DELETE_STUDENT_REQUEST'
export const DELETE_STUDENT_SUCCESS='DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAIL='DELETE_STUDENT_FAIL'

export const UPDATE_STUDENT_REQUEST='UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS='UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAIL='UPDATE_STUDENT_FAIL'

export const UPDATE_TEACHER_REQUEST='UPDATE_TEACHER_REQUEST'
export const UPDATE_TEACHER_SUCCESS='UPDATE_TEACHER_SUCCESS'
export const UPDATE_TEACHER_FAIL='UPDATE_TEACHER_FAIL'