export const STUDENT_LOGIN_REQUEST='STUDENT_LOGIN_REQUEST'
export const STUDENT_LOGIN_SUCCESS='STUDENT_LOGIN_SUCCESS'
export const STUDENT_LOGIN_FAIL='STUDENT_LOGIN_FAIL'
export const STUDENT_LOGOUT='STUDENT_LOGOUT'
 

export const GET_STUDENT_REQUEST='GET_STUDENT_REQUEST'
export const GET_STUDENT_SUCCESS='GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAIL='GET_STUDENT_FAIL'